jasypt:
   encryptor:
      password: ${jasyptpwd}
      algorithm: PBEWithMD5AndDES

server:
   port: 8080
   servlet:
      context-path: /afiliacion

tiempoHealthCheck:
   tiempo: 50000  


spring:
   datasource:
      driver-class-name: com.mysql.cj.jdbc.Driver
      type: com.zaxxer.hikari.HikariDataSource
      jdbcUrl: jdbc:mysql://localhost:3306/afiliaciones
      username: root
      password: lucia
      hikari:
         poolName: pool

spring.flyway.baseline-on-migrate: true

cache:
   time: 2
   defaultTime: 1